### ISSUE TITLE
Cannot compile with the latest version of ldc2(1.32.0)

### ISSUE THREAD

**Issue by shove70** [AuburnSounds/intel-intrinsics#127]
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(522,9): Error: undefined identifier `__builtin_ia32_clflush`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(1282,16): Error: undefined identifier `__builtin_ia32_cvtpd2dq`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(1337,16): Error: undefined identifier `__builtin_ia32_cvtpd2ps`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(1378,30): Error: undefined identifier `__builtin_ia32_cvtps2dq`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(1480,16): Error: undefined identifier `__builtin_ia32_cvtsd2si`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(1503,20): Error: undefined identifier `__builtin_ia32_cvtsd2si64`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(1657,16): Error: undefined identifier `__builtin_ia32_cvttpd2dq`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(1815,9): Error: undefined identifier `__builtin_ia32_lfence`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2150,30): Error: undefined identifier `__builtin_ia32_pmaddwd128`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2193,16): Error: undefined identifier `__builtin_ia32_maskmovdqu`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2193,9): Error: cannot return non-void from `void` function
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2365,9): Error: undefined identifier `__builtin_ia32_mfence`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2555,16): Error: undefined identifier `__builtin_ia32_pmovmskb128`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2619,16): Error: undefined identifier `__builtin_ia32_movmskpd`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2796,30): Error: undefined identifier `__builtin_ia32_pmulhw128`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2836,30): Error: undefined identifier `__builtin_ia32_pmulhuw128`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2917,30): Error: undefined identifier `__builtin_ia32_packssdw128`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2957,30): Error: undefined identifier `__builtin_ia32_packsswb128`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(2998,30): Error: undefined identifier `__builtin_ia32_packuswb128`
/root/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/emmintrin.d(3059,9): Error: undefined identifier `__builtin_ia32_pause`
Error ldc2 failed with exit code 1.

**Comment by cyrusmsk** [comment]
Errors from GitHub Actions, which uses dlang-community/setup-dlang@v1
Intel-intrinsic: 1.11.2

I have slightly different set of errors, but probably it depends on the usage of modules in code:

/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avx2intrin.d(550,30): Error: undefined identifier `__builtin_ia32_pmaddwd256`
[15](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:16)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avx2intrin.d(638,30): Error: undefined identifier `__builtin_ia32_psadbw256`
[16](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:17)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avx2intrin.d(699,30): Error: undefined identifier `__builtin_ia32_psllwi256`
[17](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:18)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avx2intrin.d(738,30): Error: undefined identifier `__builtin_ia32_pslldi256`
[18](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:19)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avx2intrin.d(802,30): Error: undefined identifier `__builtin_ia32_psrlwi256`
[19](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:20)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avx2intrin.d(846,30): Error: undefined identifier `__builtin_ia32_psrldi256`
[20](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:21)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(145,16): Error: undefined identifier `__builtin_ia32_addsubpd256`
[21](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:22)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(175,16): Error: undefined identifier `__builtin_ia32_addsubps256`
[22](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:23)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(378,16): Error: undefined identifier `__builtin_ia32_blendvpd256`
[23](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:24)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(410,16): Error: undefined identifier `__builtin_ia32_blendvps256`
[24](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:25)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(2859,16): Error: undefined identifier `__builtin_ia32_roundpd256`
[25](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:26)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(749,16): Error: template instance `inteli.avxintrin._mm256_round_pd!2` error instantiating
[26](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:27)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(2925,16): Error: undefined identifier `__builtin_ia32_roundps256`
[27](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:28)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(774,16): Error: template instance `inteli.avxintrin._mm256_round_ps!2` error instantiating
[28](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:29)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(928,16): Error: undefined identifier `__builtin_ia32_cvtpd2dq256`
[29](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:30)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(953,16): Error: undefined identifier `__builtin_ia32_cvtpd2ps256`
[30](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:31)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(979,30): Error: undefined identifier `__builtin_ia32_cvtps2dq256`
[31](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:32)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(1067,29): Error: undefined identifier `__builtin_ia32_cvttpd2dq256`
[32](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:33)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(1093,29): Error: undefined identifier `__builtin_ia32_cvttps2dq256`
[33](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/4402286915/jobs/7709291472#step:4:34)
/home/runner/.dub/packages/intel-intrinsics-1.11.2/intel-intrinsics/source/inteli/avxintrin.d(2859,16): Error: undefined identifier `__builtin_ia32_roundpd256`

**Comment by p0nce** [comment]
Need to deal with the changes in the new LDC, released yesterday.
https://forum.dlang.org/thread/azhdkaoanyqqhvosphfv@forum.dlang.org

**Comment by p0nce** [comment]
You can submit PR if interested in a quick fix

**Comment by p0nce** [comment]
https://github.com/ldc-developers/ldc/issues/4347
