### ISSUE TITLE
Doesn't build on ldc-1.12.0

### ISSUE THREAD

**Issue by CodeMyst** [AuburnSounds/intel-intrinsics#7]
```
intel-intrinsics-1.0.13/intel-intrinsics/source/inteli/xmmintrin.d(720,25): Error: undefined identifier __builtin_ia32_sqrtss, did you mean function __builtin_ia32_rsqrtss?
```

Looks like `__builtin_ia32_sqrtss` was removed from ldc.

**Comment by p0nce** [comment]
Reproduced on OSX but not Win32 for some reason https://travis-ci.org/AuburnSounds/intel-intrinsics/jobs/466594780

**Comment by p0nce** [comment]
Need a new LDC intrinsics in ldc.simd https://github.com/ldc-developers/ldc/issues/2936

**Comment by p0nce** [comment]
Fixed in v1.0.14, support LDC 1.11, LDC 1.12 and probably LDC 1.13
